name: Cloudflare Pages Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 20
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
          npm run build
          echo "Production URL: ${{ vars.PRODUCTION_URL }}"
        env:
          NODE_ENV: production
          SITE_URL: ${{ vars.PRODUCTION_URL }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          command: 'npm run build'
          packageManager: 'npm'
          projectName: 'wiki'
          directory: 'build'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}